import { Helmet } from 'react-helmet';
import Footer from '../comps/Footer';
import Navbar from '../navbar/Navbar';
import '../style/home.css'
import { useRef } from "react"
import { useState, useEffect } from "react"
import { useHistory } from "react-router-dom"
import API from '../../utils/api';
import DynamicCourseCard from '../comps/cards/DynamicCourseCard';
import { CircularProgress } from '@mui/material';
import WelcomeCourseCards from '../welcome/WelcomeCourseCards';


const SearchPage = (props) => {
    const apiCall = useRef(undefined);
    const [value, setValue] = useState(undefined)
    const history = useHistory();
    const [seacrhedResults, setSearchedResults] = useState(undefined)
    const [loading, setLoading] = useState(true)
    var phrase = props.match.params.phrase


    useEffect(() => {
        getSearchResults()
        return () => {
            if (apiCall.current !== undefined)
                apiCall.current.cancel();
        }
    }, [])
    const getSearchResults = async () => {
        try {
            apiCall.current = API.request('/product/search/', true, { phrase: phrase });
            const response = await apiCall.current.promise
            console.log(response)
            if (response.message == "Fetched successfully") {
                setSearchedResults(response.data)
            } else {
                console.log(response.message)
                setSearchedResults([])
            }
        }
        catch (err) {
            console.log(err)
        }
    }
    useEffect(() => {
        if (seacrhedResults !== undefined) {
            setLoading(false)
        }
    })
    return (
        <section>
            <Navbar />
            <div className={'containeer'}>
                <Helmet>
                    <title>بیتداد</title>
                    <meta charSet="utf-8" />
                    <meta name="description" content="Generated by aqua" />
                    <link rel="canonical" to="http://aqua.ir/" />
                    <link rel="icon" to="/favicon.ico" />
                </Helmet>
                <div className={'main'}>
                    {loading ?
                        <CircularProgress color='info' />
                        :
                        <div className='searchResultsPageWrapper'>
                            {seacrhedResults.length != 0 ?
                                <div className='searchResultsWrapper'>
                                    {seacrhedResults.map((result, index) => {
                                        return <WelcomeCourseCards key={result.id}
                                            link={`/courses/${result.id}`}
                                            bgImage={`https://api.aqua.ir:8283${result.course_info.image}`}
                                            title={result.course_info.title}
                                            description={result.course_info.short_description}
                                        />
                                    })}
                                </div>
                                : <p className='text-light'>نتیجه ای یافت نشد</p>}
                        </div>
                    }
                </div>
            </div>
            <Footer />
        </section>
    );
}

export default SearchPage;